#!/usr/bin/env bash
set -euo pipefail

DMS_COLORS_JSON="$HOME/.cache/DankMaterialShell/dms-colors.json"
FOOT_COLORS_INI="$HOME/.config/foot/colors.ini"

if [[ ! -f "$DMS_COLORS_JSON" ]]; then
  echo "sync-foot-theme-dms: missing $DMS_COLORS_JSON" >&2
  exit 1
fi

python3 - <<'PY' "$DMS_COLORS_JSON" "$FOOT_COLORS_INI"
import json, sys
from pathlib import Path

src = Path(sys.argv[1])
out = Path(sys.argv[2])

data = json.loads(src.read_text(encoding='utf-8'))

# DMS palette is already in the "dank16" + Material colors buckets
colors_dark = data['colors']['dark']
dank16 = data['dank16']

def strip_hash(hex_color: str) -> str:
    return hex_color.lstrip('#').upper()

def pick_dank_color(idx: int) -> str:
    return strip_hash(dank16[f'color{idx}']['dark'])

bg = strip_hash(colors_dark['background'])
fg = strip_hash(colors_dark['on_background'])

# Foot’s minimal palette keys we currently have in your file
regular = [pick_dank_color(i) for i in range(0, 8)]
bright = [pick_dank_color(i) for i in range(8, 16)]

selection_fg = fg
selection_bg = strip_hash(colors_dark.get('inverse_primary', colors_dark.get('primary', '#3E4953')))

# Reasonable mapping from DMS palette to Foot actions
# - urls typically a blue-ish color
urls = pick_dank_color(4)
# - jump-labels typically an accent
jump_labels = ' '.join([pick_dank_color(0), pick_dank_color(1)])

out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "\n".join([
        "# Auto-generated by DMS sync",
        "# Do not edit manually - changes will be overwritten",
        "",
        "[colors-dark]",
        f"foreground={fg}",
        f"background={bg}",
        "",
        "# Normal/regular colors (color palette 0-7)",
        *[f"regular{i}={regular[i]}" for i in range(8)],
        "",
        "# Bright colors (color palette 8-15)",
        *[f"bright{i}={bright[i]}" for i in range(8)],
        "",
        "# Cursor and selection colors",
        f"selection-foreground={selection_fg}",
        f"selection-background={selection_bg}",
        f"jump-labels={jump_labels}",
        f"urls={urls}",
        "",
    ]) + "\n",
    encoding='utf-8'
)
PY

chmod 0644 "$FOOT_COLORS_INI" || true
