-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GTK_THEME", "catppuccin-macchiato-lavender-standard+default")
hl.env("TERMINAL", "foot")

hl.on("hyprland.start", function()
	hl.exec_cmd("dms run")
	hl.exec_cmd("~/.config/hypr/scripts/bateria_status.sh")
	hl.exec_cmd("~/.config/hypr/scripts/perifericos_bateria.sh")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		kb_layout = "br",
		kb_model = "thinkpad",
		numlock_by_default = true,
		follow_mouse = 1,
		touchpad = {
			tap_to_click = true,
			natural_scroll = true,
		},
	},
	general = {
		gaps_in = 6,
		gaps_out = 12,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 14,
		active_opacity = 1.0,
		inactive_opacity = 0.95,
		dim_inactive = true,
		dim_strength = 0.03,
		shadow = {
			enabled = true,
			range = 12,
			render_power = 3,
			offset = "0 4",
			color = "rgba(00000066)",
		},
		blur = {
			enabled = true,
			size = 6,
			passes = 2,
			new_optimizations = true,
			ignore_opacity = true,
			xray = false,
			noise = 0.02,
			contrast = 0.9,
			brightness = 0.8,
			popups = true,
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 5, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 1, bezier = "default" })
hl.animation({ leaf = "layers", enabled = true, speed = 3, bezier = "default" })

hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
-- Saída virtual (ex.: sessão Plasma no tty paralelo) — sem isso o layout overlapa.
hl.monitor({ output = "WAYLAND-1", disabled = true })
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
