# CONFIGURAÇÃO DO HYPRIDLE
# Para mais info: https://wiki.hyprland.org/Hyprland-3D/Hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock          # comando para travar a tela
    before_sleep_cmd = loginctl lock-session       # trava antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on     # garante que a tela liga após acordar
}

# Reduz o brilho da tela após 2.5 minutos de inatividade
listener {
    timeout = 150                                 # 2.5 min
    on-timeout = brightnessctl -s set 10%         # reduz o brilho para 10%
    on-resume = brightnessctl -r                  # restaura o brilho anterior
}

# Trava a tela após 5 minutos de inatividade
listener {
    timeout = 300                                 # 5 min
    on-timeout = loginctl lock-session            # chama o lock_cmd (hyprlock)
}

# Desliga a tela após 5.5 minutos de inatividade
listener {
    timeout = 330                                 # 5.5 min
    on-timeout = hyprctl dispatch dpms off        # desliga o sinal do monitor
    on-resume = hyprctl dispatch dpms on          # liga novamente ao mexer o mouse/teclado
}

# Suspende o computador após 30 minutos de inatividade
listener {
    timeout = 1800                                # 30 min
    on-timeout = systemctl suspend                # suspende o sistema
}
