# CONFIGURAÇÃO DO HYPRLOCK
# Para mais info, veja: https://wiki.hyprland.org/Hyprland-3D/Hyprlock/

source = ~/.config/hypr/theme_hyprlock.conf

background {
    monitor =
    # Usa um screenshot borrado da tela como fundo
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Campo de Input (Senha)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <i>Insira a senha...</i>
    hide_input = false
    rounding = 20
    check_color = $check_color
    fail_color = $fail_color
    fail_text = <i>Senha incorreta! <b>($ATTEMPTS)</b></i>
    fail_transition = 300
    capslock_color = $capslock_color
    position = 0, -180
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
}

# Relógio (Horas)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = $label_color
    font_size = 110
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 240
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
}

# Relógio (Minutos)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $font_color
    font_size = 110
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 130
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
}

# Data
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d de %B")"
    color = $date_color
    font_size = 20
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 50
    halign = center
    valign = center
    shadow_passes = 1
}

# Foto de Perfil (Avatar)
image {
    monitor =
    path = $HOME/.config/hypr/avatar.jpg
    size = 110
    rounding = -1
    border_size = 3
    border_color = $border_color
    position = 0, -40
    halign = center
    valign = center
    shadow_passes = 1
}

# Saudação do Usuário
label {
    monitor =
    text = Olá, $USER
    color = $greet_color
    font_size = 18
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -110
    halign = center
    valign = center
    shadow_passes = 1
}
