$outer_color = rgba(cba6f7ff)
$inner_color = rgba(1e1e2edd)
$font_color = rgb(cdd6f4)
$check_color = rgba(cba6f7ff)
$fail_color = rgba(f38ba8ff)
$capslock_color = rgba(cdd6f4ff)
$border_color = rgba(cba6f7cc)
$label_color = rgba(cba6f7dd)
$date_color = rgba(cdd6f4ff)
$greet_color = rgba(cdd6f4bb)
