# Lavender Dream colors for Foot terminal
[colors-dark]
alpha=0.9
background=424874
foreground=F4EEFF
regular0=424874
regular1=DCD6F7
regular2=A6B1E1
regular3=F4EEFF
regular4=A6B1E1
regular5=DCD6F7
regular6=A6B1E1
regular7=F4EEFF
