-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(6aa4cb)",
			inactive_border = "rgb(767d83)",
		},
	},
	group = {
		col = {
			border_active = "rgb(6aa4cb)",
			border_inactive = "rgb(767d83)",
			border_locked_active = "rgb(ff7063)",
			border_locked_inactive = "rgb(767d83)",
		},
		groupbar = {
			col = {
				active = "rgb(6aa4cb)",
				inactive = "rgb(767d83)",
				locked_active = "rgb(ff7063)",
				locked_inactive = "rgb(767d83)",
			},
		},
	},
})
