-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(af9543)",
			inactive_border = "rgb(797363)",
		},
	},
	group = {
		col = {
			border_active = "rgb(af9543)",
			border_inactive = "rgb(797363)",
			border_locked_active = "rgb(ff6357)",
			border_locked_inactive = "rgb(797363)",
		},
		groupbar = {
			col = {
				active = "rgb(af9543)",
				inactive = "rgb(797363)",
				locked_active = "rgb(ff6357)",
				locked_inactive = "rgb(797363)",
			},
		},
	},
})
