-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "1920x1080@60.020", position = "0x360", scale = 1, vrr = 1 })
hl.monitor({ output = "HDMI-A-2", mode = "1920x1080@100.000", position = "1920x360", scale = 1, vrr = 0 })
