-- Auto-generated by DMS — do not edit manually
-- Fallback em "auto" evita overlap quando aparece saída virtual (ex.: WAYLAND-1).

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100.000", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "HDMI-A-2", mode = "1920x1080@100.000", position = "1920x0", scale = 1, vrr = 0 })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = 1, vrr = 1 })
hl.monitor({ output = "WAYLAND-1", disabled = true })
